version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - /psqldata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    links:
      - db:postgres
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nuveo.ai
      PGADMIN_DEFAULT_PASSWORD: nuveo
    volumes:
       - /data/pgadmin:/root/.pgadmin
    ports:
      - "80:80"
    networks:
      - postgres
    restart: unless-stopped

  rabbit:
     container_name: nuveo-rabbit
     hostname: rabbit
     image: rabbitmq:3.6.6-management
     environment:
        - RABBITMQ_DEFAULT_USER = guest
        - RABBITMQ_DEFAULT_PASS = guest
     ports:
        - "5672:5672"
        - "15672:15672"
networks:
  postgres:
    driver: bridge
